# Use the official Eclipse Mosquitto image as the base
FROM eclipse-mosquitto:latest

# Expose the default MQTT ports
EXPOSE 1883 9001

# Copy the mosquitto configuration file
COPY ./mosquitto.conf /mosquitto/config/mosquitto.conf

# Command to run the Mosquitto broker
CMD ["sh", "-c", "mosquitto -c /mosquitto/config/mosquitto.conf"]
