services:
  mqtt-broker:
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - app

networks:
  app:
    driver: bridge
